foo: bar
# These labels will be added to every created issue
labels: ["RecurringIssue"]
tickets:
   - title: "Test Issue"
     active: true
     description_file: test
     due_in_days: 7
     schedule:
       every: run
     description: "This is a test issue"
     project: misc/test_proj
     assignee: btasker
     labels: ["task", "foobar"]
