foo: bar
tickets:
   - title: "Check Softener Salt"
     active: false
     schedule:
        day: 8
        month: "*"
     description: "Check whether the softener needs more salt adding"
     project: jira-projects/HOME
     assignee: btasker
     labels: ["task"]
   - title: "Check Softener Salt"
     active: false
     schedule:
        day: 8
        month: Sep
     description: "Check whether the softener needs more salt adding"
     project: jira-projects/HOME
     assignee: btasker
     labels: ["task"]
   - title: "Check Softener Salt 3"
     active: true
     schedule:
        day: 8
        month: 1/3/8/9
     description: "Check whether the softener needs more salt adding"
     project: misc/test_proj
     assignee: btasker
     labels: ["task"]
   - title: "Check Softener Salt 4"
     active: true
     schedule:
        day: 1/3/8
        month: 1/3/8/9
     description: "Check whether the softener needs more salt adding"
     project: misc/test_proj
     assignee: btasker
     labels: ["task"]
   - title: "Worm Dogs"
     active: false
     schedule:
       every: 4 weeks
     description: "Slip the dogs a worming tablet"
     project: jira-projects/HOME
     assignee: btasker
     labels: ["task", "pets"]
   - title: "Test Issue"
     active: true
     schedule:
       every: Sun
     description: "This is a test issue"
     project: misc/test_proj
     assignee: btasker
     labels: ["task", "foobar"]
   - title: "Test Broken Issue"
     active: true
     schedule:
       every: run
     description: "This is a test issue"
     assignee: btasker
     labels: ["task", "foobar"]
